default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        types: [python]
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^((custom_components|tests)/.+)?[^/]+\.py$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=hass,alot,datas,dof,dur,farenheit,hist,iff,ines,ist,lightsensor,mut,nd,pres,referer,ser,serie,te,technik,ue,uint,visability,wan,wanna,withing
          - --skip="./.*,*.csv,*.json"
          - --quiet-level=2
        exclude_types: [csv, json]
  - repo: https://github.com/pycqa/flake8.git
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=128
        additional_dependencies:
          - flake8-docstrings
          - flake8-pyproject
          - pydocstyle
          - flake8-bugbear>=22.7.1
          - flake8-comprehensions>=3.10.1
          - flake8-2020>=1.7.0
          - mccabe>=0.7.0
          - pycodestyle>=2.9.1
          - pyflakes>=2.5.0
        files: ^(custom_components|tests|conftest)/.+\.py$
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.8'
    hooks:
      - id: bandit
        args:
          - --quiet
        files: ^(custom_components)/.+\.py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.6.0'
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.9.0'
    hooks:
      - id: mypy
        args:
          - --pretty
          - --explicit-package-bases
          - --show-error-codes
          - --show-error-context
        additional_dependencies:
          - homeassistant-stubs==2024.2.2
          - types-python-slugify==8.0.0.2
          - voluptuous-stubs==0.1.1
          - pytest
          - phonenumbers
          - async_timeout
          - RouterOS-api
  - repo: https://github.com/PyCQA/prospector
    rev: v1.10.3
    hooks:
      - id: prospector
        exclude: ^(tests)/.+\.py$
        additional_dependencies:
          - homeassistant-stubs==2024.2.2
          - types-python-slugify==8.0.0.2
          - voluptuous-stubs==0.1.1
          - pytest
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: [--check,--profile=black]
