version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: "13:00"
    groups:
      python-packages:
        patterns:
          - "*"
