site_name: Home Assistant Mikrotik SMS
site_url: https://jeyrb.github.io/hass_mikrotik_sms/
site_description: Notify via SMS text message for Mikrotik 4G modems
repo_name: jeyrb/hass_mikrotik_sms
repo_url: https://github.com/jeyrb/hass_mikrotik_sms

theme:
  name: material
  highlightjs: true
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - smarty
  - toc:
      permalink: true
  - sane_lists
  - pymdownx.snippets:
      check_paths: true
