# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: MikrotikSMS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.14"]

    steps:
    - uses: actions/checkout@v7.0.1
    - name: Install uv
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Ruff
      uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89
    - name: Test with pytest
      run: |
        uv run pytest . --junitxml=junit/test-results-${{ matrix.python-version }}.xml --cov=custom_components.mikrotik_sms --cov-report=xml --cov-report=html

    - name: HACS Action
      uses: "hacs/action@main"
      with:
        category: "integration"
        ignore: brands
    - name: Upload pytest test results
      uses: actions/upload-artifact@v7
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
    - name: Deploy docs
      # run in the build workflow since schemagen has homeassistant dependency
      run: |
        uv sync --group docs
        uv run mkdocs gh-deploy --force --config-file mkdocs.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
